title: Executive Office of the Governor
description: Executive Office of the Governor - State of Florida
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-feed

minimal_mistakes_skin: "default"
